services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: docbed-qdrant
    restart: unless-stopped
    expose:
      - 6333
      - 6444
    volumes:
      - docbed_qdrant:/qdrant/storage
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    networks:
      - docbed
    healthcheck: # curl unavailable in container, write directly to network interface
      test:
        [
          "CMD",
          "bash",
          "-c",
          "exec 3<>/dev/tcp/127.0.0.1/6333 && echo -e 'GET /readyz
            HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n'
            >&3 && grep -q 'HTTP/1.1 200' <&3",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  doc-converter:
    image: docbed-doc-converter
    build: ./doc-converter
    container_name: docbed-doc-converter
    restart: unless-stopped
    networks:
      - docbed
    expose:
      - 8000

  api:
    image: docbed-api
    build: ./api
    container_name: docbed-api
    restart: unless-stopped
    networks:
      - docbed
    ports:
      - "127.0.0.1:8000:8080"
    depends_on:
      qdrant:
        condition: service_healthy
      doc-converter:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      TogetherAI__BaseUrl: ${TOGETHERAI_BASE_URL}
      TogetherAI__ApiKey: ${TOGETHERAI_API_KEY}

networks:
  docbed:
    external: true

volumes:
  docbed_qdrant:
    external: true

configs:
  qdrant_config:
    file: qdrant.prod.yaml
